//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteHelpLogger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteHelpLogger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RHL.
        /// </summary>
        public static string strAppTitle {
            get {
                return ResourceManager.GetString("strAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change user.
        /// </summary>
        public static string strChangeUser {
            get {
                return ResourceManager.GetString("strChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user:.
        /// </summary>
        public static string strCurrentUser {
            get {
                return ResourceManager.GetString("strCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string strEnterPassword {
            get {
                return ResourceManager.GetString("strEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string strEnterUserName {
            get {
                return ResourceManager.GetString("strEnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string strLoginDialogTitle {
            get {
                return ResourceManager.GetString("strLoginDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string strLogoff {
            get {
                return ResourceManager.GetString("strLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string strOk {
            get {
                return ResourceManager.GetString("strOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop.
        /// </summary>
        public static string strProgramRDP {
            get {
                return ResourceManager.GetString("strProgramRDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Assistance.
        /// </summary>
        public static string strProgramRemoteAssistance {
            get {
                return ResourceManager.GetString("strProgramRemoteAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamViewer.
        /// </summary>
        public static string strProgramTeamViewer {
            get {
                return ResourceManager.GetString("strProgramTeamViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select program.
        /// </summary>
        public static string strSelectProgram {
            get {
                return ResourceManager.GetString("strSelectProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string strStart {
            get {
                return ResourceManager.GetString("strStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string strStop {
            get {
                return ResourceManager.GetString("strStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - none -.
        /// </summary>
        public static string strUserNone {
            get {
                return ResourceManager.GetString("strUserNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work description:.
        /// </summary>
        public static string strWorkDescr {
            get {
                return ResourceManager.GetString("strWorkDescr", resourceCulture);
            }
        }
    }
}
